name: Deploy TO Kubernetes

trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    jobs:
      - job: DeployToDev
        steps:
          - task: TerraformInstaller@2
            inputs:
             terraformVersion: 'latest'
          - task: TerraformCLI@2

            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Folder'
              backendType: 'azurerm'
              backendServiceArm: 'ForzaAzureRMConnection'
              backendAzureRmResourceGroupName: 'ForzaCapstoneResourceGroup'
              backendAzureRmResourceGroupLocation: 'eastus'
              backendAzureRmStorageAccountName: 'forzadevopstfjava'
              backendAzureRmContainerName: 'forzacapstoneaksjavadevops'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false

          - task: TerraformCLI@2
            inputs:
              command: 'plan'
              environmentServiceName: 'ForzaAzureRMConnection'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Folder'
              runAzLogin: true
              allowTelemetryCollection: false
              
          - task: TerraformCLI@2
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Folder'
              environmentServiceName: 'ForzaAzureRMConnection'
              allowTelemetryCollection: false

          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'ForzaAzureRMConnection'
              azureResourceGroup: 'ForzaCapstoneResourceGroup'
              kubernetesCluster: 'ForzaCapstoneAKSCluster-java'
              useClusterAdmin: true
              manifests: '$(System.DefaultWorkingDirectory)/Infra-Folder/deployment.yaml'
